### ISSUE TITLE
Create trust proofs

### ISSUE THREAD

**Issue by LaurenceGA** [LaurenceGA/go-crev#18]
#### Problem to solve
We need to be able to create trust proofs so the user can build their web of trust.

#### Solution
`./gocrev trust <ID>` sounds good.
We'll need a trust level and a comment.

**Comment by LaurenceGA** [comment]
@dpc hey, I'm working on implementing allowing users to create trust proofs.
I was just wanting to get some more information about ideas about how proofs are stored.

So my current understanding is that a single `.crev.proof` file is all of the proofs (separated by kind (trust or review)) for a given month, separated by a salt unique to a machine that is generated when a user sets/creates their ID. I recall this is also simply convention to make things human readable.

I was just wondering about the advantages of storing many proofs in a single file. I guess this means there are fewer files, so less clutter.
I guess one drawback is it hinders the ability to share proofs individually (not that there's a use case at the moment :shrug: )
I suppose this partially comes from the PEM format crev proofs are based on? (I was hoping to parse them with [an existing library](https://golang.org/pkg/encoding/pem/), but it seems will require a custom (de)serialisation)

I was thinking for my implementation of storing 1 proof per file. They could be put in folders by time or something for sorting convenience. Then to avoid [merge conflict issues](https://github.com/crev-dev/cargo-crev/issues/153) each proof could be given its own UUID :thinking: 

Just wondering what you thought? You feedback is appreciated :grin:

**Comment by LaurenceGA** [comment]
Also, do you let user's create trust proofs for themselves? How does cargo crev handle that?
(I guess they can always manually create one if they really want to, even if the CLI stops them... :thinking: )

**Comment by dpc** [comment]
> So my current understanding is that a single .crev.proof file is all of the proofs (separated by kind (trust or review)) for a given month

The whole structure is just a convention and crev clients should just recursively scan all `.crev.proof` files.

The current convention seems to be working OK, but it might need to be improved once we start hitting real life issues (repos grow big, people run aggregators etc.)

> there are fewer files, so less clutter.

I was more concered about the performance of checkouts / switching branches / scanning the directory. Humans being able to navigate stuff easier is nice but secondary, IMO.

> I guess one drawback is it hinders the ability to share proofs individually

There should be easy commands that export / import proofs. Users should dig into repos manually only for ... donno... debugging, or maybe when doing string search in github or something.

> I suppose this partially comes from the PEM format crev proofs are based on?

I actually have not based it on PEMs. I was mostly imitating armoered gpg output, while stuffing a yaml in it.

> I was hoping to parse them with an existing library, but it seems will require a custom (de)serialisation

Yeah. You can check the parsing code
https://github.com/crev-dev/cargo-crev/blob/6ea38175baa351bfdda0da500afdd0e41876ab2f/crev-data/src/proof/mod.rs#L199

- nothing too fancy about it. Just a simple state-machine looking for these `--- SOMETHING ---` lines.

> Also, do you let user's create trust proofs for themselves? How does cargo crev handle that?


I'm not sure what you ask about exactly. `cargo-crev` has a really nice interactive proof editing system - modeled after `git commit` editing. I think you should definitely check it yourself - eg. by downloading the binaries. I might prepare a recording of it too.

**Comment by dpc** [comment]
Very old recording that I did: https://asciinema.org/a/216695 . Some stuff about editing proof changed, but the spirit is the same.

**Comment by LaurenceGA** [comment]
Thanks for the info! Very helpful - good to get an idea of what design decisions have already been made.

> I was more concered about the performance of checkouts / switching branches / scanning the directory

Ah okay. Can't be that impactful can it? Same amount of data, but I guess fewer sys calls to open files? 🤔 

> I was mostly imitating armoered gpg output, while stuffing a yaml in it.

I see. According to the [go package for pgp armor format](https://pkg.go.dev/golang.org/x/crypto/openpgp/armor?tab=doc#pkg-overview), it's basically PEM + a checksum.

> I'm not sure what you ask about exactly

Sorry, I wasn't clear. I was just wondering if there was special logic for the user typing something like `cargo-crev trust <myself>`. Just curious.

**Comment by dpc** [comment]
> `cargo-crev trust <myself>`

Oh. I haven't really consider this much, except distrusting your own id is a way to mark your id as compromised and a sign for other people that they should not use it anymore.
